In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.6'

In [3]:
import sys
sys.version

'3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)]'

In [ ]:
my_list = [0,1,2,3,4,5] #Creating a List 
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

we are convering list to array

In [7]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [9]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [11]:
type(my_list)

list

In [ ]:
np.   # we learn important function .+tab

SyntaxError: invalid syntax (153258804.py, line 1)

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
 np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [21]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [23]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
np.arange(20,10) # 1st arg <2nd arg

array([], dtype=int64)

In [28]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [30]:
np.arange(10,30,5) # 10- string from 30- end point 5 - step count

array([10, 15, 20, 25])

In [33]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [34]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [35]:
np.zeros(10) # parameter tunning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros(5, dtype = 'int') #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [38]:
np.zeros((2,2), dtype = 'int')

array([[0, 0],
       [0, 0]])

In [39]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [40]:
zero = np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [43]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.zeros((10,10), dtype ='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [46]:
np.ones(3)

array([1., 1., 1.])

In [48]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.ones(4, dtype = 'int')

array([1, 1, 1, 1])

In [50]:
np.ones(4)

array([1., 1., 1., 1.])

In [51]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [52]:
rand(3,2)

NameError: name 'rand' is not defined

In [53]:
random.rand(3,2)

NameError: name 'random' is not defined

In [58]:
np.random.rand(3,2)

array([[0.33883697, 0.88134016],
       [0.00868384, 0.7384052 ],
       [0.54990262, 0.12493929]])

In [59]:
np.rand(3,2)

AttributeError: module 'numpy' has no attribute 'rand'

In [62]:
np.random.rand(5)

array([0.62114001, 0.87003268, 0.98190045, 0.42922012, 0.48401841])

In [63]:
np.random.rand(3,5)

array([[0.08922945, 0.43475669, 0.02028347, 0.05688513, 0.35848171],
       [0.67936755, 0.08156569, 0.90213179, 0.91680586, 0.88359698],
       [0.61835955, 0.55977763, 0.48177226, 0.96709857, 0.68189251]])

In [69]:
np.random.randint(4,6)

5

In [137]:
np.random.randint(2,20,4) #2nd argument is exclusive

array([18,  9,  8,  7], dtype=int32)

In [107]:
np.random.randint(0,1)

0